server:
  port: 8080

spring:
  application:
    name: api-gateway

  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: never
      include-exception: false

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # =====================================
            # ROUTE ĐẾN CUSTOMER SERVICE
            # =====================================
            - id: customer-service-route
              uri: lb://customer-service
              predicates:
                - Path=/auth/**,/customers/**,/admin/customers/**

            # =====================================
            # ROUTE ĐẾN CAR SERVICE
            # =====================================
            - id: car-service-route
              uri: lb://car-service
              predicates:
                - Path=/cars/**,/manufacturers/**,/suppliers/**

            # =====================================
            # ROUTE ĐẾN RENTING SERVICE
            # =====================================
            - id: renting-service-route
              uri: lb://renting-service
              predicates:
                - Path=/rentings/**

          # Thời gian chờ khi Gateway gọi service khác
          httpclient:
            connect-timeout: 3000
            response-timeout: 10s

# =====================================
# EUREKA CLIENT
# =====================================
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true

# =====================================
# ACTUATOR
# =====================================
management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

# =====================================
# JWT
# Phải giống chính xác secret bên Customer Service
# =====================================
jwt:
  secret: ${JWT_SECRET:0123456789012345678901234567890123456789012345678901234567890123}